parameters:
- name: myParameter
  type: string
  default: 'defaultValue'

pool:
  name: ubuntu-latest

steps:
- checkout: none
- script: |
    waiting for completion
    echo $(testvar)
    sleep 30
  displayName: 'wait 600 seconds'
